#!/bin/bash

function canonicalize
{
	cd -P -- "$(dirname -- "$1")" &&
	printf '%s\n' "$(pwd -P)/$(basename -- "$1")"
}

basedir=`canonicalize $0`
basedir=`dirname $basedir`

if [ "$#" -lt "1" ]; then
 arch=`${basedir}/../dirac-platform.py`                 || exit 1
 prefixDir=${basedir}/../$arch
else
 prefixDir=$1
fi
mkdir -p ${prefixDir}                          || exit 1
#
Version=0.4

function installGSI
{
	(
		cd $basedir
		
		rm -f site.cfg
		echo "library_dirs=${prefixDir}/lib" > site.cfg
		echo "include_dirs=${prefixDir}/include" >> site.cfg

		INSTALLbin=`canonicalize $prefixDir/bin`
		INSTALLlib=`canonicalize $prefixDir/lib`
		export PATH=$INSTALLbin:$PATH
		python=`which python` ; python=`canonicalize $python`
		DIRACpython=`canonicalize $INSTALLbin/python`
		python_version=`$python -V 2>&1 | awk '{print $2}' | awk -F. '{printf "%s.%s",$1,$2}'` || exit 1
		$python setup.py build                                     || exit 1
		$python setup.py bdist_egg                                 || exit 1
		echo "HERE"
		rm -rf temp                                                || exit 1
		mkdir temp                                                 || exit 1
		(
			cd temp
			python $basedir/unzip.py ../dist/pyGSI-${Version}-py${python_version}-*-*.egg  || exit 1
			rm -rf EGG-INFO                                            || exit 1
			if [ $python == $DIRACpython ] ; then
			  cp -r * ${INSTALLlib}/python${python_version}/site-packages/ || exit 1
			fi
		)
	)
}

installGSI