#!/bin/bash

basedir=`readlink -f $0`
basedir=`dirname $basedir`
#
Version=1.2.2
sslVersion=0.9.7m

openssldir=$basedir/../../external/openssl-${sslVersion}


if ! [ -d $openssldir ] ; then
  echo This package needs "$openssldir"
  exit 1
fi

(
cd $basedir
arch=`../../scripts/dirac-architecture`
DIRACdir=`readlink -f $basedir/../..`
DIRACbin=$DIRACdir/$arch/bin
DIRAClib=$DIRACdir/$arch/lib

export PATH=$DIRACbin:$PATH
python setup.py install
python_version=`python -V 2>&1 | awk '{print $2}' | awk -F. '{printf "%s.%s",$1,$2}'`
python=`which python` ; python=`readlink -f $python`
python_arch=`file $python | awk '{ if ( $0 ~ "x86-64" ) print "-x86_64"; if ( $0 ~ "IA-64" ) print "-ia64" }'`
CONTRIBdir=$DIRACdir/contrib/python${python_version}${python_arch}
mkdir -p $CONTRIBdir
rm -rf $CONTRIBdir/OpenSSL
cp -r $DIRAClib/python${python_version}/site-packages/OpenSSL $CONTRIBdir
)
